"""Small, dependency-free foundations for AI-AutoCut."""

from .boundary_guard import (
    BoundaryGuardContractError,
    GuardIssue,
    GuardReport,
    GuardSegment,
    run_boundary_guard,
)
from .executable_timeline import (
    BACKENDS,
    COMPILER_STATUS,
    ExecutableTimeline,
    ExecutableTimelineContractError,
    TimelineSegment,
    compile_for_backend,
    parse_executable_timeline,
    render_executable_timeline,
)
from .frame_boundary import (
    BoundaryAssessment,
    CandidateSlice,
    FrameAlignmentError,
    FrameBoundaryError,
    Placement,
    ReadbackMismatchError,
    ReadbackVerification,
    SourceRange,
    TimelineGeometryError,
    absolute_timeline_frame,
    assert_not_before_timeline_start,
    assess_candidate_cut,
    assess_source_boundary,
    build_relative_placements,
    frames_to_seconds_exact,
    seconds_to_frame_exact,
    verify_placement_readback,
)

from .gold_manifest import (
    ASSET_STATUSES,
    GOLD_STATUSES,
    GoldAssetReference,
    GoldManifest,
    GoldManifestContractError,
    MasterRecord,
    VisualAuthority,
    assert_not_promoted,
    parse_gold_manifest,
    render_gold_manifest,
    sha256_of_file,
    verify_asset_reference,
)
from .paths import (
    ENV_ASCII_STAGING,
    ENV_DAVINCI_PATH,
    ENV_JIANYING_PATH,
    ENV_LEGACY_WORKSPACE,
    ENV_MEDIA_ROOT,
    ENV_WORKSPACE,
    PathConfiguration,
    PathConfigurationError,
    assert_ascii_safe,
    find_machine_paths,
    is_ascii_safe,
    looks_like_machine_path,
)

__all__ = [
    "BoundaryGuardContractError",
    "BoundaryAssessment",
    "CandidateSlice",
    "FrameAlignmentError",
    "FrameBoundaryError",
    "GuardIssue",
    "GuardReport",
    "GuardSegment",
    "Placement",
    "ReadbackMismatchError",
    "ReadbackVerification",
    "SourceRange",
    "TimelineGeometryError",
    "absolute_timeline_frame",
    "assert_not_before_timeline_start",
    "assess_candidate_cut",
    "assess_source_boundary",
    "build_relative_placements",
    "frames_to_seconds_exact",
    "run_boundary_guard",
    "seconds_to_frame_exact",
    "verify_placement_readback",

    # path configuration
    "ENV_ASCII_STAGING",
    "ENV_DAVINCI_PATH",
    "ENV_JIANYING_PATH",
    "ENV_LEGACY_WORKSPACE",
    "ENV_MEDIA_ROOT",
    "ENV_WORKSPACE",
    "PathConfiguration",
    "PathConfigurationError",
    "assert_ascii_safe",
    "find_machine_paths",
    "is_ascii_safe",
    "looks_like_machine_path",

    # gold manifest
    "ASSET_STATUSES",
    "GOLD_STATUSES",
    "GoldAssetReference",
    "GoldManifest",
    "GoldManifestContractError",
    "MasterRecord",
    "VisualAuthority",
    "assert_not_promoted",
    "parse_gold_manifest",
    "render_gold_manifest",
    "sha256_of_file",
    "verify_asset_reference",
    # executable timeline
    "BACKENDS",
    "COMPILER_STATUS",
    "ExecutableTimeline",
    "ExecutableTimelineContractError",
    "TimelineSegment",
    "compile_for_backend",
    "parse_executable_timeline",
    "render_executable_timeline",
]
